/*
 * Texturen
 */
	const string SPRINT_MENU_CHOICE_BACK_PIC	= "menu_choice_back.tga";	// Hintergrund für Choicebox

/*
 * Fonts
 */
	const string SPRINT_MENU_FONT_DEFAULT		= "font_old_10_white.tga";
	
/*
 * Actions
 */
	const int SPRINT_SEL_ACTION_UNDEF			= 0;
	const int SPRINT_SEL_ACTION_BACK			= 1;
	const int SPRINT_SEL_ACTION_STARTMENU		= 2;

/*
 * Dimensions
 */	
 	const int SPRINT_MENU_SLIDER_DX				= 2000;
	const int SPRINT_MENU_TITLE_Y				= 1200;
	const int SPRINT_MENU_BACK_Y				= 6500;
	const int SPRINT_MENU_CHOICE_DY				= 350;
	const int SPRINT_MENU_CHOICE_YPLUS			= 120;

	const int SPRINT_MENU_START_Y				= 2400;
	const int SPRINT_MENU_DY					= 650;	

/*
 * Types
 */
	const int SPRINT_MENU_ITEM_TEXT				= 1;
	const int SPRINT_MENU_ITEM_INPUT			= 3;
	const int SPRINT_MENU_ITEM_CHOICEBOX		= 5;
	
/*
 * Flags
 */
	const int SPRINT_IT_SELECTABLE				= 4;
	const int SPRINT_SEL_ACTION_EXECCOMMANDS	= 7;
	const int SPRINT_IT_TXT_CENTER				= 16;
	const int SPRINT_MENU_SHOW_INFO				= 64;
	const int SPRINT_IT_EFFECTS_NEXT			= 128;

/*
 * Text Title
 */
	const string SPRINT_TITLE_EN				= "INFINITE SPRINT V.2";
	const string SPRINT_TITLE_DE				= "DAUERHAFTES RENNEN V.2";
	const string SPRINT_TITLE_PO				= "CIAGLE WYSCIGI V.2";
	const string SPRINT_TITLE_RU				= "NEPRERYVNAJa GONKA V.2";
 